### ISSUE TITLE
different results from the python script vs from webpage (possibly due to the default wmv value?)

### ISSUE THREAD

**Issue by fanwei918** [CenterForTheBuiltEnvironment/comfort_tool#10]
Thanks for developing this nice tool.  For a quick going-through, I tried using the comfort_models.py to calculate the PMV value in such condition:

Air Temp: 25
Mean Ra Temp: 25
Air speed: 0.1
humidity (relative humidity): 50
met rate: 1.1
clothing: 0.5

this is the example values shown on the http://comfort.cbe.berkeley.edu/  page, if choosing "temperature - Relative humidity chart" option. the result provided on the webpage is
PMV -0.13
PPD 5 %
Sensation Neutral
SET 24.6°C
 
I used the comfPMVElevatedAirspeed() function in the comfort_models.py script. This function requires one more input wme, from the comments of codes it mentioned that this value is usually around 0, so I chose wme = 0. it derived results as:
PMV -0.13201636244868287
PPD: 5.361054624642392, 
SET: 24.523854581903315 C

the PMV , PPD are in accordance with result from the web page, considering rounding the digits. However, the SET temp has slight difference, considering rounding, the 2 results still don't agrees. So I am wondering :
Is this due to my choice of  WME(=0) is not a default value? if so, what is the default value of wme to make sure the python script's result is exactly equal to the web page result?

**Comment by FedericoTartarini** [comment]
Unfortunately there was an issue with the while loop. Please initialize TCL_OLD = False. That should solve the issue. A new version of the code will soon be available for download.
