### ISSUE TITLE
Solar Cal tool

### ISSUE THREAD

**Issue by FedericoTartarini** [CenterForTheBuiltEnvironment/comfort_tool#18]
1. It would be good to make an actual help page for solarcal rather than just link to the paper. I think this is really key to making people start to use this feature because right now no one understands how to use this. Perhaps we even put in a graphic directly in the pop-up window that graphically explains what each parameter is. Also, the help button should open a new window, not go directly to the paper.
2. Short of graphics explaining each parameter, the variables (e.g. [Tsol]) should be made into tool tips where a user can hover over them and get an explanation of what they mean. I think the same thing should also be done for the local discomfort popup.
3. While I don’t think it is terribly important, it would be nice to have a location selector field, where a user inputs zip code or city name or latitude and the Idir is automatically determined and populated from the location
4. I’m wondering if “solar gain on occupants” should be a check box or if we have some more direct way of alerting users that they need to consider solar gain in order to comply with Std 55—so they need to actually input whether it is a factor or not. Same for local discomfort. I think both of these sections get ignored and they are requirements of the standard, so I think we should find a way to make people notice them.
5. Eventually it would also be nice to build in the solar addendum prescriptive approach tables to the tool. So instead of entering all the solarcal inputs, you would enter your glass properties and shade type and the tool would do a lookup to determine if you comply

**Comment by Lila-Laura** [comment]
Dear Mr. Tartarini,
I just read your comments on the SolarCalc tool and found them to be very true. Thanks for sharing! I was wondering where to get the code of the SolarCalc extension as I didn't find it within the project. Do you know where how to access the code? As I am currently working on an advanced comfort tool I would love to get an insight in the coding of the tool.
Thanks a lot in advance! 
Greetings from Munich 
Laura

**Comment by FedericoTartarini** [comment]
Hi Laura, the above comments are suggested enhancements that are not yet implemented. The code of the SolarCal extension can be found here: https://github.com/CenterForTheBuiltEnvironment/comfort_tool/blob/master/static/js/erf.js line 154
