### ISSUE TITLE
Old feature list from google code

### ISSUE THREAD

**Issue by thoyt** [CenterForTheBuiltEnvironment/comfort_tool#2]
1.  An experimental mean radiant temperature calculation tool using graphical methods. (Tyler, almost done)
2.  Heat loss vs air temperature chart: color coded areas display the different components of heat loss using both the PMV and the SET models. The representation is updated by changing the RH, mean radiant temperature, air speed, met and clo values.
3.  Visualization of annual data using the adaptive comfort model. The goal is to upload a weather file and display the hourly data on a time-temperature chart throughout the year, to see the distribution of the adaptive comfort zone compared to the outdoor conditions. (the code already exists, but the upload has to be implemented)
4.  Develop a chart that shows air speed (x-axis) vs cooling effect (y-axis) as a function of Tair with MRT=Tair only for v=0.2 m/s. PMV should be an input and the default should be 0.5. The set of lines should change with met, clo, and RH.
5.  Interoperability and visualizations of data from external sources: a user may be interested in visualizing simulated or empirical data within the psychrometric chart. This will allow a designer to explore conditions that will provide a high level of comfort. The prevailing outdoor air temperature may also be calculated from a weather file. Add possibility to download the calculated values. (Tyler)
6.  Upload a weather file from internet and calculate:
   Adaptive comfort prevailing mean temperature (Alberto has already the file working with weather file)
   Clothing model
   Compare different climates. This can be done both in the adaptive and PMV/PPD method.
7. Monte carlo markov chain simulation of PMV (Tyler, Atsunori, Toby)
8. Give an option (check box) to plot the PPD value for each point in the graph. Legend should be displayed
9. Add the psychrometric variables to the RH-dry-bulb chart
10. Develop and new reppresentation of the the humid air, e.g. dry-bulb temperature vs enthalpy or dry-bulb vs wet-bulb
11. Add the Nicol's graph (difference between outdoor and comfort temp). Useful to understand the need of heating and cooling. Look at email from Sue Roaf on July 22 2016

**Comment by FedericoTartarini** [comment]
I have addressed the following issues 1, 2, 9.
