### ISSUE TITLE
Code for SolarCalc

### ISSUE THREAD

**Issue by Lila-Laura** [CenterForTheBuiltEnvironment/comfort_tool#29]
Dear contributors,

where can I find the code for the SolarCalc tool? I am currently working with the CBE tool and would love to get a look at it. Love your tool! :-) 

Looking forward to your response.

Greetings from Munich
Laura

**Comment by Lila-Laura** [comment]
Would be great if you could just post the link!

**Comment by FedericoTartarini** [comment]
Hi @Lila-Laura you can find the [Python code here](https://pythermalcomfort.readthedocs.io/en/latest/_modules/pythermalcomfort/models.html#solar_gain) and the [JS code here](https://github.com/CenterForTheBuiltEnvironment/comfort_tool/blob/master/static/js/erf.js)
