### ISSUE TITLE
Strict input validation

### ISSUE THREAD

**Issue by thoyt** [CenterForTheBuiltEnvironment/comfort_tool#3]
The input fields all have limits that are imposed by the spinner buttons. However you can always just type in whatever you want in the field, which can sometimes cause the tool to crash if the value is either (a) very large, causing NaNs to be output by the comfort models or (b) invalid (e.g. a metabolic rate of "cat").

Two possible solutions: 
1. Strictly validate the input. If a number can't be parsed or is out of range, give a warning and replace the input with the default. (easier)
2. Allow inputs out of range, but if NaNs are encountered during the computation, quit safely.

**Comment by FedericoTartarini** [comment]
I have implemented solution 1.
