### ISSUE TITLE
Creating a way to save the results.

### ISSUE THREAD

**Issue by stefanoschiavon** [CenterForTheBuiltEnvironment/comfort_tool#45]
One of the most requested features that we had in the past and then removed was the LEED documentation. We remove it because it was broken. We received many emails asking it back. We may add it back. 
A simpler option would be to have the saving/restore/share feature available in the CBE fan tool
https://centerforthebuiltenvironment.github.io/fan-tool/

**Comment by FedericoTartarini** [comment]
I have implemented the save, reload and share functionality. I have opened another issue for the LEED
