### ISSUE TITLE
Using JSON string

### ISSUE THREAD

**Issue by bill-orange** [CenterForTheBuiltEnvironment/comfort_tool#5]
Rather than using the interactive model, can I pass a JSON string to the python code and get a ASHRAE reply?  If so how.

**Comment by chriswmackey** [comment]
@bill-orange ,

I'm sure that someone could write a short script pretty quickly that parses a json and calculates comfort. You could use either the Python or the JavaScript functions for thermal comfort on this github to do so as a json is easily read-able in both languages. The specifics of the script would depend on how you structure you json, though. Is there a specific reason why you ask about this?

-Chris

**Comment by thoyt** [comment]
The interactive sites is driven by the JavaScript thermal comfort functions, so there's no need for an internal API that would take JSON as input. It could be created using the Python functions as a backend.
