### ISSUE TITLE
CBE Thermal Comfort Tool: bug in Ranges

### ISSUE THREAD

**Issue by CsillaVG** [CenterForTheBuiltEnvironment/comfort_tool#55]
Hi, 
There is a bug in Ranges which is triggered when Clothing level is selected (in the top drop down menu) and the user wants to modify the Metabolic rate. The code seem to end up in a loop/hanging.
Best,
Csilla

**Comment by FedericoTartarini** [comment]
Thank you for letting us know, I have fixed the issue
