### ISSUE TITLE
Local discomfort is not working 

### ISSUE THREAD

**Issue by SnapDragon123321** [CenterForTheBuiltEnvironment/comfort_tool#61]
Hello. Whenever I change values for local discomfort evaluations nothing happens. It was working nicely before. Changing browsers or devices did not help, so I believe there is a problem from your side. Please fix. Thank you.

**Comment by FedericoTartarini** [comment]
@SnapDragon123321 could you please share more information about the error? Which of the many discomfort models is not working?

**Comment by SnapDragon123321** [comment]
@FedericoTartarini I attached some screenshots. 
![Screenshot_5](https://user-images.githubusercontent.com/81955278/113665313-1171cf00-96cf-11eb-8990-94481dfe7794.jpg)

No green ticks or red crosses appear after values were changed
![Screenshot_6](https://user-images.githubusercontent.com/81955278/113665321-1898dd00-96cf-11eb-9554-d3e66742e1da.jpg)

Comparison with the later version (Thank you very much for creating a separate block)
![Screenshot_7](https://user-images.githubusercontent.com/81955278/113665453-5269e380-96cf-11eb-8caf-b5a65cde1a6e.jpg)

**Comment by FedericoTartarini** [comment]
Thank you for your feedback I have fixed the issue in version 2.1.5

Please let me know if you experience any other issues.
