### ISSUE TITLE
PMV values exceeding 3.0

### ISSUE THREAD

**Issue by ajebach** [CenterForTheBuiltEnvironment/comfort_tool#67]
Hi CBE,

I have used your Comfort Indices Upload Tool and got some potential errors. 

The conditions I have are quite extreme, an indoor assembly factory for seated workers during summer.

Below is the outputs from just a few of the time points. The PMV values I get for some of these more extreme conditions exceed 3.0. 

Is that an error within the calculation? Should I simply round down to 3 as it should be the maximum of the scale?

ta | tr | vel | rh | met | clo | clo_dynamic | **pmv**
33.5 | 34.6 | 0.21 | 70.2 | 3.1 | 1.21 | 0.882 | **3.25**
35.7 | 35.8 | 0.56 | 62.7 | 3 | 0.91 | 0.667 | **3.24**
36.3 | 37.4 | 0.23 | 59.6 | 3 | 0.54 | 0.396 | **3.32**

Thanks :)

**Comment by FedericoTartarini** [comment]
Hi, getting a value of PMV higher than 3 is not an issue. The PMV model can return any value. 

On the other hand, it should be noted that as stated in the ISO 7730 and in Fanger's book the PMV model should only be used for |PMV| < 2, hence, for any value higher than 2 or lower than -2 the PMV should be used with extreme caution.

Source: Fanger, P. O. (1970). Thermal comfort: analysis and applications in environmental engineering. McGraw-Hill, New York.
![image](https://user-images.githubusercontent.com/40018640/157584801-b8322dca-7fd2-4115-b752-eb15c1772a0f.png)
