### ISSUE TITLE
ASHRAE 55 2020 addenda

### ISSUE THREAD

**Issue by Steve1812023** [CenterForTheBuiltEnvironment/comfort_tool#79]
What addenda to ASHRAE 55 2020 are included in your version 2,5.3 of the Thermal Comfort Tool? Is there a later version that includes the addenda related to the formulas for the calculations? If so, how do I get access to it?

**Comment by FedericoTartarini** [comment]
The tool should be up to date and to my knowledge it does include all the changes in up to Addendum k.

**Comment by Steve1812023** [comment]
Federico:
When I use the PMV method of the program and input a Met rate of over 2.0, the program comes up with a warning near the top in red stating “Does not comply with the ASHRAE Standard 55-2020. Metabolic rates below 1.0 or above 2.0 are not covered by this Standard”. This is the former max the 55-2020 said was the upper limit for it’s application before addendum b changed it to 4.0 in item “5.2.1.4 High Metabolic Rates”. Addendum b and the following addendums appeared to try to change the standard from a typical office environment evaluation to include an industrial and heavy labor environment (Table 5.1 has always included labor categories up to Met =  4.0/4.8).

Addendum H “Approved by ASHRAE and the American National Standards Institute on December 30, 2022” made some pretty substantial changes to the standard and the programming. In correspondence with the ASHRAE technical committee, they indicated that a compendium document for the standard and all its addenda does not exist and they “hope” the committee will produce an updated version of Standard 55 in the normal cycle for 2023. Given the fact that the 2020 version came out in 2021, I don’t hold out much hope that the new updated 2023 version will come out before 2024.

Sorry for rambling and I know it’s not your issue but I’m trying to reach a sound result that I can use for the evaluation of the need and capacity for air conditioning in an industrial environment with time averaged Met rates in the 2.4 range.

Please let me know your thoughts.
Steve Lemmo, PE

Steven Lemmo PE | Halliwell
Senior Mechanical Engineer
***@***.******@***.***>
+1 401.965.2082 | mobile
www.halliwellglobal.com<http://www.halliwellglobal.com/>

[Icon  Description automatically generated]

CONFIDENTIALITY AND PRIVILEGE NOTICE: The information contained in this message and any attachments may be privileged, confidential and/or exempt from disclosure under applicable law. Any views expressed in this message and any attachments are those of the individual sender, except where the message states otherwise, and in no way binds Insurers and/or their representatives. If you are not the intended recipient, you are hereby notified that any use, dissemination, distribution, or reproduction of any information contained herein or attached is strictly prohibited. If you have received this email in error, please immediately notify the sender and destroy the original transmission and its attachments, without reading them. All professional engineering services performed in California, Connecticut, Illinois, New York, and North Carolina are provided through Halliwell Engineering P.A. In all other states professional services are performed by Halliwell Engineering Associates, LLC.

**Comment by FedericoTartarini** [comment]
# Addendum B
Yes, you are correct, Addendum b has changed the max met to 4. I will fix this. Please note that I do not personally think the PMV model is really valid for such high Mets and you should be very sceptical of the results.

> Could the Warning notice that pops up with Met rates over 2.0 simply be a warning that was not taken out of the program when it was updated with the addenda? The program continues to give results up to the 2.5 Met rate I used.

Yes, I think this is the case, I forgot to remove the warning. I will look into it.

# Addendum H
It should be included in the CBE Thermal comfort tool but if you spot any issues please let me know. The source code and all the Changelogs are publicly available.

On a side note please write comments from GitHub and please do not reply to this email since replying via email add a lot of unwanted text.

**Comment by FedericoTartarini** [comment]
I fixed the issue. I removed the warning message that was displayed to the user for 2<met<4

**Comment by Steve1812023** [comment]
Thanks Frederico.
